// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: weather.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Weather {
  public static partial class WeatherService
  {
    static readonly string __ServiceName = "weather.WeatherService";

    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    static readonly grpc::Marshaller<global::Weather.WeatherRequest> __Marshaller_weather_WeatherRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Weather.WeatherRequest.Parser));
    static readonly grpc::Marshaller<global::Weather.WeatherResult> __Marshaller_weather_WeatherResult = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Weather.WeatherResult.Parser));
    static readonly grpc::Marshaller<global::Weather.WeatherHistoricReply> __Marshaller_weather_WeatherHistoricReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Weather.WeatherHistoricReply.Parser));

    static readonly grpc::Method<global::Weather.WeatherRequest, global::Weather.WeatherResult> __Method_RequestCurrentWeatherData = new grpc::Method<global::Weather.WeatherRequest, global::Weather.WeatherResult>(
        grpc::MethodType.Unary,
        __ServiceName,
        "RequestCurrentWeatherData",
        __Marshaller_weather_WeatherRequest,
        __Marshaller_weather_WeatherResult);

    static readonly grpc::Method<global::Weather.WeatherRequest, global::Weather.WeatherHistoricReply> __Method_RequestHistoricData = new grpc::Method<global::Weather.WeatherRequest, global::Weather.WeatherHistoricReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "RequestHistoricData",
        __Marshaller_weather_WeatherRequest,
        __Marshaller_weather_WeatherHistoricReply);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Weather.WeatherReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of WeatherService</summary>
    [grpc::BindServiceMethod(typeof(WeatherService), "BindService")]
    public abstract partial class WeatherServiceBase
    {
      /// <summary>
      /// Sends the current weather information
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      public virtual global::System.Threading.Tasks.Task<global::Weather.WeatherResult> RequestCurrentWeatherData(global::Weather.WeatherRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Sends the a stream of weather data
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      public virtual global::System.Threading.Tasks.Task<global::Weather.WeatherHistoricReply> RequestHistoricData(global::Weather.WeatherRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(WeatherServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_RequestCurrentWeatherData, serviceImpl.RequestCurrentWeatherData)
          .AddMethod(__Method_RequestHistoricData, serviceImpl.RequestHistoricData).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, WeatherServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_RequestCurrentWeatherData, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Weather.WeatherRequest, global::Weather.WeatherResult>(serviceImpl.RequestCurrentWeatherData));
      serviceBinder.AddMethod(__Method_RequestHistoricData, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Weather.WeatherRequest, global::Weather.WeatherHistoricReply>(serviceImpl.RequestHistoricData));
    }

  }
}
#endregion
