// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package weather

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// WeatherServiceClient is the client API for WeatherService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WeatherServiceClient interface {
	// Sends the current weather information
	RequestCurrentWeatherData(ctx context.Context, in *WeatherRequest, opts ...grpc.CallOption) (*WeatherResult, error)
	// Sends the a stream of weather data
	RequestHistoricData(ctx context.Context, in *WeatherRequest, opts ...grpc.CallOption) (*WeatherHistoricReply, error)
}

type weatherServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWeatherServiceClient(cc grpc.ClientConnInterface) WeatherServiceClient {
	return &weatherServiceClient{cc}
}

func (c *weatherServiceClient) RequestCurrentWeatherData(ctx context.Context, in *WeatherRequest, opts ...grpc.CallOption) (*WeatherResult, error) {
	out := new(WeatherResult)
	err := c.cc.Invoke(ctx, "/weather.WeatherService/RequestCurrentWeatherData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *weatherServiceClient) RequestHistoricData(ctx context.Context, in *WeatherRequest, opts ...grpc.CallOption) (*WeatherHistoricReply, error) {
	out := new(WeatherHistoricReply)
	err := c.cc.Invoke(ctx, "/weather.WeatherService/RequestHistoricData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WeatherServiceServer is the server API for WeatherService service.
// All implementations must embed UnimplementedWeatherServiceServer
// for forward compatibility
type WeatherServiceServer interface {
	// Sends the current weather information
	RequestCurrentWeatherData(context.Context, *WeatherRequest) (*WeatherResult, error)
	// Sends the a stream of weather data
	RequestHistoricData(context.Context, *WeatherRequest) (*WeatherHistoricReply, error)
	mustEmbedUnimplementedWeatherServiceServer()
}

// UnimplementedWeatherServiceServer must be embedded to have forward compatible implementations.
type UnimplementedWeatherServiceServer struct {
}

func (UnimplementedWeatherServiceServer) RequestCurrentWeatherData(context.Context, *WeatherRequest) (*WeatherResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestCurrentWeatherData not implemented")
}
func (UnimplementedWeatherServiceServer) RequestHistoricData(context.Context, *WeatherRequest) (*WeatherHistoricReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestHistoricData not implemented")
}
func (UnimplementedWeatherServiceServer) mustEmbedUnimplementedWeatherServiceServer() {}

// UnsafeWeatherServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WeatherServiceServer will
// result in compilation errors.
type UnsafeWeatherServiceServer interface {
	mustEmbedUnimplementedWeatherServiceServer()
}

func RegisterWeatherServiceServer(s grpc.ServiceRegistrar, srv WeatherServiceServer) {
	s.RegisterService(&WeatherService_ServiceDesc, srv)
}

func _WeatherService_RequestCurrentWeatherData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WeatherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeatherServiceServer).RequestCurrentWeatherData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/weather.WeatherService/RequestCurrentWeatherData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeatherServiceServer).RequestCurrentWeatherData(ctx, req.(*WeatherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WeatherService_RequestHistoricData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WeatherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeatherServiceServer).RequestHistoricData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/weather.WeatherService/RequestHistoricData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeatherServiceServer).RequestHistoricData(ctx, req.(*WeatherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WeatherService_ServiceDesc is the grpc.ServiceDesc for WeatherService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WeatherService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "weather.WeatherService",
	HandlerType: (*WeatherServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestCurrentWeatherData",
			Handler:    _WeatherService_RequestCurrentWeatherData_Handler,
		},
		{
			MethodName: "RequestHistoricData",
			Handler:    _WeatherService_RequestHistoricData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "weather.proto",
}
